name: Duolingo README Stats Action

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: Update readme with your duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: centrumek/duolingo-readme-stats@main
        with:
          DUOLINGO_USER_ID: ${{ secrets.DUOLINGO_USER_ID }}
          ADVANCED_TOKEN_JWT: ${{ secrets.DUOLINGO_JWT_TOKEN }}
          SHOW_ADVANCED_LEAGUE: true
          SHOW_ADVANCED_XP_THIS_WEEK: true
          SHOW_LANGUAGES: false
